### ISSUE TITLE
lzfse decode issue - msys2 build

### ISSUE THREAD

**Issue by P5-2005** [lzfse/lzfse#61] opened 2022-09-11 10:44 UTC
compile success over msys2(win10x64)
encode all fine
only issue is with decode :

decoding file of 14mb, RAM increase insanely like 5GB+
then output :

```
malloc: Not enough space
```

**Comment by Artoria2e5** [comment] 2023-03-14 14:40
possible duplicate of #47.

**Closed as not planned** 2023-10-18 10:26 UTC
